# Generated by Django 3.2.4 on 2023-04-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_remove_registration_behance_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='hacker_rank_username',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='year',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='your_work',
        ),
    ]
